apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sealed-secrets-controller
rules:
  - apiGroups: ['bitnami.com']
    resources: ['sealedsecrets']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'delete']
