apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taiga
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/OAKDEW/gitops-devs/tree/master/projects/devops/taiga'
    path: environments/prod
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: taiga
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
