apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/OAKDEW/gitops-devs/applications'
    path: gitlab/prod
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/OAKDEW/gitops-devs/applications'
    path: nginx-ingress/prod
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/OAKDEW/gitops-devs/applications'
    path: sealed-secrets/prod
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taiga
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/OAKDEW/gitops-devs/applications'
    path: taiga/prod
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
