apiVersion: v1
kind: Namespace
metadata:
  name: devops

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops
  namespace: argocd
spec:
  description: 'Development Operations project to setup OAKDEW CI/CD pipeline'
  sourceRepos:
    - 'https://github.com/OAKDEW/gitops-devs'
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: 'devops'
  clusterResourceAllowList:
    - group: '*'
      kind: '*'
