apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-provisioner
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      containers:
        - name: nfs-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - mountPath: /exports
              name: nfs-export
          env:
            - name: PROVISIONER_NAME
              value: kubernetes.io/nfs
            - name: NFS_SERVER
              value: k8s-iris
            - name: NFS_PATH
              value: /srv/kubernetes-volumes
      volumes:
        - name: nfs-export
          nfs:
            server: k8s-iris
            path: /srv/kubernetes-volumes
