apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: taiga
  name: taiga-env
data:
  DEFAULT_FROM_EMAIL: ''
  EMAIL_HOST_USER: ''
  EMAIL_PORT: '587'
  EMAIL_USE_SSL: false
  EMAIL_USE_TLS: true
  EMAIL_BACKEND: django.core.mail.backends..EmailBackend
  EMAIL_HOST: ''
  ENABLE_TELEMETRY: ''
  MAX_AGE: '360'
  POSTGRES_USER: taiga
  POSTGRES_DB: taiga
  POSTGRES_HOST: taiga-db
  RABBITMQ_USER: taiga
  RABBITMQ_DEFAULT_USER: taiga
  RABBITMQ_DEFAULT_VHOST: taiga
  SUBPATH: ''
  TAIGA_SCHEME: https
  TAIGA_DOMAIN: localhost:9000
  TAIGA_URL: ://
  TAIGA_WEBSOCKETS_URL: ://
  TAIGA_SITES_DOMAIN: ''
  TAIGA_SITES_SCHEME: ''
  TAIGA_SUBPATH: ''
  WEBSOCKETS_SCHEME: ws
