apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: taiga
  name: taiga-protected
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga
  template:
    metadata:
      labels:
        app: taiga
    spec:
      containers:
        - name: taiga-protected
          image: taigaio/taiga-protected:latest
          envFrom:
            - configMapRef:
                name: taiga-env
            - secretRef:
                name: taiga-secrets
      restartPolicy: Always
