apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: taiga
  name: taiga-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga
  template:
    metadata:
      labels:
        app: taiga
    spec:
      containers:
        - image: taigaio/taiga-events:latest
          name: taiga-events
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: taiga-env
            - secretRef:
                name: taiga-secrets
      restartPolicy: Always
