apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga-events
  template:
    metadata:
      labels:
        app: taiga-events
    spec:
      containers:
        - name: taiga-events
          image: taigaio/taiga-events:latest
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: taiga-config
            - secretRef:
                name: taiga-secrets
          env:
            - name: TAIGA_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: taiga-config
                  key: SECRET_KEY
