apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: taiga
  name: taiga-events-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: taiga
    spec:
      containers:
        - name: taiga-events-rabbitmq
          image: rabbitmq:3.8-management-alpine
          envFrom:
            - configMapRef:
                name: taiga-env
            - secretRef:
                name: taiga-secrets
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: taiga-events-rabbitmq-data
      hostname: taiga-events-rabbitmq
      restartPolicy: Always
      volumes:
        - name: taiga-events-rabbitmq-data
          persistentVolumeClaim:
            claimName: taiga-events-rabbitmq-data
