resources:
  - deploy-async.yaml
  - deploy-async-rabbitmq.yaml
  - deploy-back.yaml
  - deploy-db.yaml
  - deploy-events.yaml
  - deploy-events-rabbitmq.yaml
  - deploy-gateway.yaml
  - deploy-protected.yaml
  - deploy-front.yaml
  - pvc-async-rabbitmq-data.yaml
  - pvc-db-data.yaml
  - pvc-events-rabbitmq-data.yaml
  - pvc-media-data.yaml
  - pvc-static-data.yaml
  - pv-async-rabbitmq-data.yaml
  - pv-db-data.yaml
  - pv-events-rabbitmq-data.yaml
  - pv-media-data.yaml
  - pv-static-data.yaml
  - service-gateway.yaml
  - configmap-gateway-cm0.yaml
  - configmap.yaml
  - secret.yaml
