apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga-postgresql
  template:
    metadata:
      labels:
        app: taiga-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:12.3
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: taiga-config
            - secretRef:
                name: taiga-secrets
          volumeMounts:
            - name: postgresql-storage
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          securityContext:
            runAsUser: 999
          command: ['/bin/sh', '-c']
          args:
            - >
              pg_ctl -D "$PGDATA" -o "-c listen_addresses=''" -w start &&
              psql -U postgres -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'postgres') THEN CREATE ROLE postgres LOGIN SUPERUSER PASSWORD '${POSTGRES_PASSWORD}'; END IF; END \$\$;" &&
              pg_ctl -D "$PGDATA" -m fast -w stop &&
              docker-entrypoint.sh postgres
      volumes:
        - name: postgresql-storage
          persistentVolumeClaim:
            claimName: taiga-postgresql-pvc
