apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-taiga-async-rabbitmq-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/disks/taiga/async-rabbitmq-data
  storageClassName: local-storage
