apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-taiga-db-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/disks/taiga/db-data
  storageClassName: taiga-local-storage
