apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-taiga-events-rabbitmq-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/disks/taiga/events-rabbitmq-data
  storageClassName: local-storage
