apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-taiga-media-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/disks/taiga/media-data
  storageClassName: taiga-local-storage
