apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: taiga
  name: taiga-static-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
