apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: taiga
  name: taiga-async-rabbitmq-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: taiga-local-storage
