apiVersion: v1
kind: PersistentVolume
metadata:
  name: taiga-rabbitmq-async-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/taiga/rabbitmq-async
