apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga-rabbitmq
  template:
    metadata:
      labels:
        app: taiga-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: taiga-config
                  key: RABBITMQ_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: taiga-secrets
                  key: RABBITMQ_PASS
            - name: RABBITMQ_ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: taiga-secrets
                  key: RABBITMQ_ERLANG_COOKIE
          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: taiga-rabbitmq-async-pvc
