apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga-events
  template:
    metadata:
      labels:
        app: taiga-events
    spec:
      containers:
        - name: taiga-events
          image: taigaio/taiga-events:latest
          ports:
            - containerPort: 8888
          env:
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: taiga-config
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: taiga-secrets
                  key: RABBITMQ_PASS
            - name: TAIGA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: taiga-secrets
                  key: TAIGA_SECRET_KEY
