apiVersion: v1
kind: Secret
metadata:
  name: taiga-secrets
type: Opaque
data:
  EMAIL_HOST_PASSWORD: YkpSU2FHM0RCWGpZTDV5NW12MnR4RDNjVVhGS1JuUw==
  POSTGRES_PASSWORD: UTJTbW11Njh0MkJlUGNneThGV282MjNzM0xTbG1HaXZTZzczU2ZOSg==
  RABBITMQ_PASS: bWxKa3R1NjVCOENtZGc4N0d3N2xnQnl2UnhZRENIaXdwTTZQVmo0bA==
  RABBITMQ_DEFAULT_PASS: bWxKa3R1NjVCOENtZGc4N0d3N2xnQnl2UnhZRENIaXdwTTZQVmo0bA==
  RABBITMQ_ERLANG_COOKIE: dHFsYzZVNGx3eTc5dWRpeFk4VVBCWjREUG90dm55dWptNTk1RVJZNTQ=
  SECRET_KEY: TXY0V3BTVDVRSjcyN25CbUNoTWJHd1FuS3c3NDRUdGNRaGI0NW9pMg==
  TAIGA_SECRET_KEY: TXY0V3BTVDVRSjcyN25CbUNoTWJHd1FuS3c3NDRUdGNRaGI0NW9pMg==
