apiVersion: v1
kind: Service
metadata:
  labels:
    app: taiga
  name: taiga-db
spec:
  selector:
    app: taiga
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
