apiVersion: v1
kind: Service
metadata:
  labels:
    app: taiga
  name: taiga-back
spec:
  selector:
    app: taiga
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
