apiVersion: v1
kind: Namespace
metadata:
  name: devops

---
apiVersion: argoproj.io/v1alpha1
kind: Project
metadata:
  name: devops
  namespace: argocd
spec:
  description: 'Project to manage the tools for Development Operations'
  sourceRepos:
    - 'https://github.com/OAKDEW/gitops-devs'
  destinations:
    - namespace: 'devops'
      server: 'https://kubernetes.default.svc'
