apiVersion: argoproj.io/v1alpha1
kind: Project
metadata:
  name: devops
  namespace: devops
  labels:
    environment: production
  annotations:
    description: 'Development Operation project to manage the developmenet tools'
spec:
  sourceRepos:
    - 'https://github.com/OAKDEW/gitops-devs'

  destinations:
    - namespace: devops
      server: 'https://kubernetes.default.svc'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  automatedSync:
    prune: true
    selfHeal: true
