apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: default
data:
  vault.hcl: |
    storage "file" {
      path = "/vault/file"
    }

    ui = true

    audit "file" {
      file_path = "/vault/logs/audit.log"
    }

    auth "kubernetes" {}

    secrets "kv" {
      path = "secret/"
    }
