apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/vault
  storageClassName: manual
