apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops
spec:
  project: devops
  source:
    repoURL: 'https://github.com/OAKDEW/gitops-devs/projects/nfs'
    targetRevision: master
    path: devops
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
