apiVersion: v1
kind: Service
metadata:
  name: taiga-async-rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      name: rabbitmq
    - port: 15672
      targetPort: 15672
      name: rabbitmq-management
  selector:
    app: taiga-async-rabbitmq
