apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/OAKDEW/gitops-devs/tree/master/projects/devops/nginx-ingress'
    path: base
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
