apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga-back
  template:
    metadata:
      labels:
        app: taiga-back
    spec:
      containers:
        - name: taiga-back
          image: taigaio/taiga-back:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: taiga-config
            - secretRef:
                name: taiga-secrets
          volumeMounts:
            - name: static-storage
              mountPath: /taiga-back/static
            - name: media-storage
              mountPath: /taiga-back/media
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: static-storage
          persistentVolumeClaim:
            claimName: taiga-static-pvc
        - name: media-storage
          persistentVolumeClaim:
            claimName: taiga-media-pvc
