apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-front
  namespace: taiga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga-front
  template:
    metadata:
      labels:
        app: taiga-front
    spec:
      restartPolicy: Always
      containers:
        - name: taiga-front
          image: taigaio/taiga-front:latest
          ports:
            - containerPort: 80
          env:
            - name: TAIGA_URL
              valueFrom:
                configMapKeyRef:
                  name: taiga-config
                  key: TAIGA_URL
            - name: TAIGA_WEBSOCKETS_URL
              valueFrom:
                configMapKeyRef:
                  name: taiga-config
                  key: TAIGA_WEBSOCKETS_URL
            - name: TAIGA_SUBPATH
              valueFrom:
                configMapKeyRef:
                  name: taiga-config
                  key: TAIGA_SUBPATH
            - name: GITLAB_URL
              valueFrom:
                configMapKeyRef:
                  name: taiga-config
                  key: GITLAB_URL_FRONT
            - name: ENABLE_GITLAB_AUTH
              value: 'true'
            - name: PUBLIC_REGISTER_ENABLED
              value: 'true'
            - name: GITLAB_API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: taiga-secret
                  key: GITLAB_API_CLIENT_ID
            - name: GITLAB_API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: taiga-secret
                  key: GITLAB_OAUTH2_CLIENT_ID
            - name: GITLAB_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: taiga-secret
                  key: GITLAB_API_CLIENT_SECRET
            - name: GITLAB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: taiga-secret
                  key: GITLAB_API_CLIENT_SECRET
          resources:
            requests:
              memory: '256Mi'
              cpu: '200m'
            limits:
              memory: '512Mi'
              cpu: '400m'
