apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taiga
  namespace: devops
spec:
  ingressClassName: nginx
  rules:
    - host: taiga.oakdew.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taiga-gateway
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taiga-gateway
                port:
                  number: 443
