apiVersion: v1
kind: Service
metadata:
  name: taiga-back
spec:
  type: NodePort
  selector:
    app: taiga-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: taiga-db
spec:
  selector:
    app: taiga-db
  ports:
    - protocol: TCP
      port: 5432
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: taiga-front
spec:
  type: NodePort
  selector:
    app: taiga-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: taiga-async
spec:
  type: NodePort
  selector:
    app: taiga-async
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: taiga-async-rabbitmq
spec:
  selector:
    app: taiga-async-rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: rabbitmq
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: rabbitmq-management

---
apiVersion: v1
kind: Service
metadata:
  name: taiga-events-rabbitmq
spec:
  selector:
    app: taiga-events-rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: rabbitmq
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: rabbitmq-management

---
apiVersion: v1
kind: Service
metadata:
  name: taiga-gateway
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: taiga-gateway
