apiVersion: v1
kind: Service
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  type: NodePort
  selector:
    app: sealed-secrets
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
