apiVersion: v1
kind: ConfigMap
metadata:
  name: taiga-config
data:
  TAIGA_DB_NAME: taiga
  TAIGA_DB_USER: taiga_user
  TAIGA_ALLOWED_HOSTS: taiga.yourdomain.com
  TAIGA_DB_HOST: taiga-db
  TAIGA_DB_PORT: '5432'
