apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga-front
  template:
    metadata:
      labels:
        app: taiga-front
    spec:
      containers:
        - name: taiga-front
          image: taigaio/taiga-front:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: '256Mi'
              cpu: '200m'
            limits:
              memory: '512Mi'
              cpu: '400m'
          readinessProbe:
            httpGet:
              path: '/'
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: '/'
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
