apiVersion: v1
kind: Secret
metadata:
  name: taiga-secret
type: Opaque
data:
  POSTGRES_PASSWORD: eSptc1FnNEZGI00zNDk3V3VZSDhWelFtYSFIcXM5SEYkUG8zUG9tRA==
  SECRET_KEY: Q0pGWEhucWxSZioqbmwqNkU3c1JuZTcjRmVTcERtZVJsQUE1SzlENw==
