apiVersion: v1
kind: Service
metadata:
  name: taiga-back
spec:
  type: NodePort
  selector:
    app: taiga-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: taiga-front
spec:
  type: NodePort
  selector:
    app: taiga-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
