apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
data:
  worker-processes: '1'
  http-snippet: |
    server {
      listen 80;
      location / {
        return 200 'nginx ingress controller is working';
      }
    }
